ASP.NETSaturdayProject/ASP.NETSaturdayProject/Models/Food.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ASP.NETSaturdayProject.Models
{
    public class Food
    {
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string cuisine { get; set; }
        [Required]
        public decimal price { get; set; }
        [Required]
        public int Quantity { get; set; } 
    }
}

ASP.NETSaturdayProject/ASP.NETSaturdayProject/Models/sorting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASP.NETSaturdayProject.Models
{
    public class sorting
    {
        public string SortName { get; set; }
        public bool dsort { get; set; }
    }
}

ASP.NETSaturdayProject/ASP.NETSaturdayProject/Controllers/FoodController.cs
using ASP.NETSaturdayProject.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP.NETSaturdayProject.Controllers
{
    public class FoodController : Controller
    {

        SqlConnection con = new SqlConnection(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\rohan\Documents\DBFoodManager.mdf;Integrated Security=True;Connect Timeout=30");

        public List<Food> GetFoodData()
        {
            SqlCommand cmd = new SqlCommand("Select * from TBLFoods", con);

            List<Food> foods = new List<Food>();

            con.Open();

            SqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                Food temp = new Food();
                temp.id = reader.GetInt32(0);
                temp.name = reader.GetString(1);
                temp.cuisine = reader.GetString(2);
                temp.price = reader.GetDecimal(3);
                temp.Quantity = reader.GetInt32(4);

                foods.Add(temp);
            }

            con.Close();

            return foods;
        }

        public ActionResult GetFoods()
        {
            return View("FoodsList", GetFoodData());
        }

        public ActionResult GotoInsert()
        {
            return View("InsertFood");
        }

        public ActionResult InsertFood(Food f)
        {
            if (ModelState.IsValid)
            {
                SqlCommand cmd = new SqlCommand("insert into TBLFoods values ('" + f.name + "','" + f.cuisine + "'," + f.price + "," + f.Quantity + ")", con);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();

                return RedirectToAction("GetFoods");
            }
            else
            {
                return View("InsertFood");
            }
        }

        public ActionResult GotoVDA()
        {
            return View("VDAView", GetFoodData());
        }

        public ActionResult DeleteClickedVDA(Food f)
        {
            SqlCommand cmd = new SqlCommand("DELETE from TBLFoods where id="+f.id, con);
            con.Open();
            cmd.ExecuteNonQuery();
            con.Close();
            return View("VDAView", GetFoodData());
        }

        public ActionResult InsertFoodVDA(Food f)
        {
            SqlCommand cmd = new SqlCommand("insert into TBLFoods values ('" + f.name + "','" + f.cuisine + "'," + f.price + "," + f.Quantity + ")", con);
            con.Open();
            cmd.ExecuteNonQuery();
            con.Close();

            return View("VDAView", GetFoodData());
        }

        public ActionResult UpdateFoodVDA(Food f)
        {
            SqlCommand cmd = new SqlCommand("update TBLFoods SET Name = '" + f.name + "', Cuisine = '" + f.cuisine + "', Price = " + f.price + ", Quantity = " + f.Quantity + " WHERE ID = " + f.id, con);
            con.Open();
            cmd.ExecuteNonQuery();
            con.Close();

            return View("VDAView", GetFoodData());
        }

        public ActionResult Sorting(sorting s)
        {
            List<Food> foods = GetFoodData();

            for (int i = 0; i < foods.Count; ++i)
            {
                for (int j = i + 1; j < foods.Count; ++j)
                {
                    if(s.SortName == "ID")
                    {
                        if(s.dsort)
                        {
                            List<Food> SortedList = foods.OrderByDescending(o => o.id).ToList();
                            foods = SortedList;
                        }
                        else
                        {
                            List<Food> SortedList = foods.OrderBy(o => o.id).ToList();
                            foods = SortedList;
                        }
                    }
                    if (s.SortName == "NAME")
                    {
                        if (s.dsort)
                        {
                            List<Food> SortedList = foods.OrderByDescending(o => o.name).ToList();
                            foods = SortedList;
                        }
                        else
                        {
                            List<Food> SortedList = foods.OrderBy(o => o.name).ToList();
                            foods = SortedList;
                        }
                    }
                    if (s.SortName == "CUISINE")
                    {
                        if (s.dsort)
                        {
                            List<Food> SortedList = foods.OrderByDescending(o => o.cuisine).ToList();
                            foods = SortedList;
                        }
                        else
                        {
                            List<Food> SortedList = foods.OrderBy(o => o.cuisine).ToList();
                            foods = SortedList;
                        }
                    }
                    if (s.SortName == "PRICE")
                    {
                        if (s.dsort)
                        {
                            List<Food> SortedList = foods.OrderByDescending(o => o.price).ToList();
                            foods = SortedList;
                        }
                        else
                        {
                            List<Food> SortedList = foods.OrderBy(o => o.price).ToList();
                            foods = SortedList;
                        }
                    }
                    if (s.SortName == "QUANTITY")
                    {
                        if (s.dsort)
                        {
                            List<Food> SortedList = foods.OrderByDescending(o => o.Quantity).ToList();
                            foods = SortedList;
                        }
                        else
                        {
                            List<Food> SortedList = foods.OrderBy(o => o.Quantity).ToList();
                            foods = SortedList;
                        }
                    }
                }
            }

            return View("VDAView", foods);
        }
    }
}

ASP.NETSaturdayProject/ASP.NETSaturdayProject/Views/Food/FoodsList.cshtml
@using ASP.NETSaturdayProject.Models
@model List<Food>
<div class="container">
    <h1> List of Foods</h1>
    <table class="table table-dark">
        <tr>
            <td>ID</td>
            <td>NAME</td>
            <td>CUISINE</td>
            <td>PRICE</td>
            <td>QUANTITY</td>
        </tr>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].id</td>
                <td>@Model[i].name</td>
                <td>@Model[i].cuisine</td>
                <td>@Model[i].price</td>
                <td>@Model[i].Quantity</td>
            </tr>
        }
    </table>
</div>

ASP.NETSaturdayProject/ASP.NETSaturdayProject/Views/Food/InsertFood.cshtml
@using ASP.NETSaturdayProject.Models
@model Food


<div class="container">
    <h1>Insert Food</h1>

    @using (Html.BeginForm("InsertFood", "Food", FormMethod.Post, new { Class = "form-group container" }))
    {
        @Html.TextBoxFor(a => a.name, new { Class = "form-control mt-2", PlaceHolder = "Enter Food Name" })
        @Html.ValidationMessageFor(a => a.name, "", new { Class = "text-danger" })
        @Html.TextBoxFor(a => a.cuisine, new { Class = "form-control mt-2", PlaceHolder = "Enter Food Cuissine" })
        @Html.ValidationMessageFor(a => a.cuisine, "", new { Class = "text-danger" })
        @Html.TextBoxFor(a => a.price, new { Class = "form-control mt-2", PlaceHolder = "Enter Food Price" })
        @Html.ValidationMessageFor(a => a.price, "", new { Class = "text-danger" })
        @Html.TextBoxFor(a => a.Quantity, new { Class = "form-control mt-2", PlaceHolder = "Enter Food Quantity" })
        @Html.ValidationMessageFor(a => a.Quantity, "", new { Class = "text-danger" })
        <input type="submit" class="form-control btn btn-dark mt-2" />
    }
</div>

ASP.NETSaturdayProject/ASP.NETSaturdayProject/Views/Food/VDAView.cshtml
@using ASP.NETSaturdayProject.Models
@model List<Food>

<div class="container">
    <h1> List of Foods</h1>
    <table class="table table-dark">
        <tr>
            <td>@Html.ActionLink("Sort", "Sorting", "Food", new { SortName = "ID", dsort = false}, new { Class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("Sort", "Sorting", "Food", new { SortName = "NAME", dsort = false }, new { Class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("Sort", "Sorting", "Food", new { SortName = "CUISINE", dsort = false }, new { Class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("Sort", "Sorting", "Food", new { SortName = "PRICE", dsort = false }, new { Class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("Sort", "Sorting", "Food", new { SortName = "QUANTITY", dsort = false }, new { Class = "btn btn-primary" })</td>
        </tr>

        <tr>
            <td>ID</td>            
            <td>NAME</td>
            <td>CUISINE</td>
            <td>PRICE</td>
            <td>QUANTITY</td>
            <td>Delete</td>
        </tr>

        @foreach (Food fd in Model)
        {
            <tr>
                <td>@fd.id</td>
                <td>@fd.name</td>
                <td>@fd.cuisine</td>
                <td>@fd.price</td>
                <td>@fd.Quantity</td>
                <td>@Html.ActionLink("Delete", "DeleteClickedVDA", "Food", fd, new { Class = "btn btn-danger", id = "button" + fd.id })</td>
            </tr>
        }

        @using (Html.BeginForm("InsertFoodVDA", "Food", FormMethod.Post, new { Class = "form-inline" }))
        {
            <tfoot>
                <tr>
                    <td>
                        <span class="gg-add-r bg-success mt-1"></span>
                    </td>
                    <td>
                        @Html.TextBox("name", "", new { Class = "form-control", PlaceHolder = "Enter Food Name" })
                        @Html.ValidationMessage("name", "", new { Class = "text-danger" })
                    </td>
                    <td>
                        @Html.TextBox("cuisine", "", new { Class = "form-control", PlaceHolder = "Enter Cuisine Name" })
                        @Html.ValidationMessage("cuisine", "", new { Class = "text-danger" })
                    </td>
                    <td>
                        @Html.TextBox("price", "", new { Class = "form-control", PlaceHolder = "Enter Price" })
                        @Html.ValidationMessage("price", "", new { Class = "text-danger" })
                    </td>
                    <td>
                        @Html.TextBox("Quantity", "", new { Class = "form-control", PlaceHolder = "Enter Quantity" })
                        @Html.ValidationMessage("Quantity", "", new { Class = "text-danger" })
                    </td>
                    <td>
                        <input type="submit" class="form-control btn btn-success" />
                    </td>
                </tr>
            </tfoot>
        }
    </table>
</div>

ASP.NETSaturdayProject/ASP.NETSaturdayProject/Views/Shared/MyLayout.cshtml
<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/CSS-Icons.css" rel="stylesheet" />
    <link href="~/Content/fontawesome.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "GetFoods", "Food", null, new { Class = "nav-link" })
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Menu
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Insert", "GotoInsert", "Food", null, new { Class = "dropdown-item" })
                        @Html.ActionLink("View, Delete, Add", "GotoVDA", "Food", null, new { Class = "dropdown-item" })
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    @RenderBody()
    <footer class="page-footer font-small pt-4 bg-light text-dark">

        <!-- Footer Links -->
        <div class="container-fluid text-center text-md-left">

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-6 mt-md-0 mt-3">

                    <!-- Content -->
                    <h5 class="text-uppercase">Footer Content</h5>
                    <p>Here you can use rows and columns to organize your footer content.</p>

                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">

                <!-- Grid column -->
                <div class="col-md-3 mb-md-0 mb-3">

                    <!-- Links -->
                    <h5 class="text-uppercase">Links</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a href="#!" class="text-primary">Link 1</a>
                        </li>
                        <li>
                            <a href="#!" class="text-primary">Link 2</a>
                        </li>
                        <li>
                            <a href="#!" class="text-primary">Link 3</a>
                        </li>
                        <li>
                            <a href="#!" class="text-primary">Link 4</a>
                        </li>
                    </ul>

                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-3 mb-md-0 mb-3">

                    <!-- Links -->
                    <h5 class="text-uppercase">Links</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a href="#!" class="text-primary">Link 1</a>
                        </li>
                        <li>
                            <a href="#!" class="text-primary">Link 2</a>
                        </li>
                        <li>
                            <a href="#!" class="text-primary">Link 3</a>
                        </li>
                        <li>
                            <a href="#!" class="text-primary">Link 4</a>
                        </li>
                    </ul>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Links -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © 2020 Copyright:
            <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
        </div>
        <!-- Copyright -->

    </footer>
</body>
</html>
<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
@Scripts.Render("~/bundles/jqueryval")